# Default Configuration
spring:
  application:
    name: greentrace-server
  
  # Database Configuration (H2 for testing)
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # H2 Console (for testing)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # Server Configuration
  server:
    port: 8080
  
  # Security Configuration
  security:
    jwt:
      secret: ${JWT_SECRET:mySecretKey}
      expiration: 86400000 # 24 hours in milliseconds

# Logging Configuration
logging:
  level:
    com.greentrace.server: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"