# Default Configuration
spring:
  application:
    name: greentrace-server
  
  # Database Configuration (H2 for testing)
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # H2 Console (for testing)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  # Security Configuration
  security:
    jwt:
      secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: 86400000 # 24 hours in milliseconds

# Server Configuration
server:
  port: 8080

# Application Configuration
app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}

# Logging Configuration
logging:
  level:
    com.greentrace.server: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"